### ISSUE TITLE
Possible resulting dataset(s) availability

### ISSUE THREAD

**Issue by filak** [dis-unige/eahil2018#2]
You have done a great job!

I have two questions:
1) I just wonder whether you have published your results data somewhere ?

2) Have you asked to NLM to integrate your data - DOIs - in PubMed/MEDLINE database ? (or replicate your steps to enrich their data)

**Comment by pablogit** [comment]
Sorry @filak for the delay in the answer, the closing of the issue reminded me that we had never answered your questions >:-o

1. Unfortunately we did not release the data because we are still working on the project and we are trying to repeat the process with the data updated in 2019. Hopefully we will publish the results and share the data this year but for the moment we are too busy with the current work (in Switzerland research is practically a voluntary activity and is done outside working hours in university libraries)

2. We also plan to do so once we have published our results

But we can discuss all this next week in Basel ;-)
